### PR TITLE
Fix cookie authentication in node and browser

### PR DESCRIPTION
**Pull request by layanto**
Fix https://github.com/redgeoff/slouch/issues/44 and https://github.com/redgeoff/slouch/issues/10

### CODE REVIEW

**Comment by layanto** [comment]
I don't know how to fix the CI error

**Comment by redgeoff** [comment]
Cool, I'll have to take a closer look. It looks like there is not enough tests to cover 100%. See https://github.com/redgeoff/slouch/blob/master/TESTING.md#automated-browser-tests

Also, https://github.com/redgeoff/slouch/blob/2ea58b9a039667725c28c446f6d38fde80637362/test/spec/user.js#L243 and https://github.com/redgeoff/slouch/blob/2ea58b9a039667725c28c446f6d38fde80637362/test/spec/user.js#L187 need to be modified so that these tests also run in the browser.

**Comment by layanto** [comment]
I am not good with automated testing. I think Line 243 of spec/user.js should work for both node and browser (selenium). Line 187 of spec/user.js I think should be deleted as already covered by Line 243.

**Comment by layanto** [comment]
Need new spec to test sliding window cookie authentication where persistent cookie is turned off. I have manually tested this on node and browser.

**Comment by redgeoff** [comment]
Hey @layanto! Sorry for the delay. I took a look and this looks good on the surface. Here are a few comments:
- I think we still need `should authenticate and get session` test as it tests `authenticateAndGetSession`. See my comment above about uncommenting the tests
- It looks like a unit test is failing: https://circleci.com/gh/redgeoff/slouch/332?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by layanto** [comment]
From memory there was no fail on unit tests before I pushed the last commit - https://github.com/redgeoff/slouch/pull/108/commits/eb2c8a713bbba4d010cd23c3c621f61afdc5c3b8

**Comment by layanto** [comment]
That unit test passes now though I don't know why that code is needed because the new code that looks out for set-cookie header should be doing exactly the same thing.

**Comment by layanto** [comment]
@redgeoff How do I find out which lines of code are missed in the coverage test?

**Comment by redgeoff** [comment]
```
$ npm run node-full-test
You can then view the test coverage by opening cache/coverage/node/lcov-report/index.html in a browser
```

See [TESTING.md](https://github.com/redgeoff/slouch/blob/master/TESTING.md) for this and more

**Comment by layanto** [comment]
I don't actually have the test environment setup, I was relying on your CircleCI but unable to access the coverage report.

**Comment by redgeoff** [comment]
Besides node, the only other test dependency is CouchDB. If you have Docker installed, you can [run CouchDB with Docker](https://github.com/redgeoff/slouch/blob/master/TESTING.md#option-b-running-couchdb-in-docker)

**Comment by layanto** [comment]
Found the missing coverage:
image

It is because couchDB does not send set-cookie in header in the first ~10% of cookie time (I think default is 10mins). So test script needs to wait at least 1 minute between couch request for couch to respond with set-cookie in header.

**Comment by layanto** [comment]
Actually that line of code is expected to not execute in browser as browser doesn't return set-cookie in response. How can I tell Istanbul to skip that line but only in browser test?

**Comment by redgeoff** [comment]
There is a way to tell istanbul to ignore the coverage for all tests, but this will also affect the node test. Instead, you should be able to mock the data with something like https://github.com/redgeoff/slouch/pull/108/files#diff-31d0244dd9f2b3e5473ffa03302aca50L188

**Comment by layanto** [comment]
> There is a way to tell istanbul to ignore the coverage for all tests, but this will also affect the node test. Instead, you should be able to mock the data with something like https://github.com/redgeoff/slouch/pull/108/files#diff-31d0244dd9f2b3e5473ffa03302aca50L188

Not sure about mocking it to pass code coverage test as it means in browser test that code will execute when in actual browser, that code will never execute. I think it is better to skip code coverage test for both node and browser and add a node only test case to make sure the intent of the code is actioned (in node, whenever couchdb updates set-cookie in response, slouch automatically updates its internal cookie). This already happened as before I skip code coverage test, there was no problem with node code coverage test.

**Comment by redgeoff** [comment]
@layanto nice work! Thanks for sticking with it.

**Comment by layanto** [comment]
Hopefully you will release 1.2.0 soon.

**Comment by redgeoff** [comment]
Planning on it in the next couple days ;)

**Pull request merged**
