### PR TITLE
added missing _design term for view

### PR DESCRIPTION
**Pull request by akralj**
Views are not working - so I added the missing _design word.

### CODE REVIEW

**Comment by redgeoff** [comment]
Thanks for the PR. The id of a design doc includes the '_design/' prefix so the current functionality is correct. That being said, to preserve compatibility with a nano like call I'd suggest the following changes. Could you please make them?

1. Create a function `_designNameToDocId(designNameOrDocId)` which searches for the `_design\` string and if it does **not** exist prepends it
2. Then use this function in the view and viewArray functions
3. Create a new unit test that will cover the flow where a `_design\` is missing from the call to view()

I can help you if you get stuck.

Thanks!

**Comment by akralj** [comment]
Hi. I am calling the view like with:
```
slouch.db.view("datadb", "getIdsToUpdate", "getIdsToUpdate").each
```
Its working with the changes is made in the PR, but not with your original code. how should i call a view?
thanks & thanks for your great lib
andrej

**Comment by redgeoff** [comment]
The current way to make this work is like

```js
slouch.db.view("datadb", "_design/getIdsToUpdate", "getIdsToUpdate").each()
```

**Comment by akralj** [comment]
thanks, that works. maybe you add it to the docs...

**Comment by redgeoff** [comment]
I agree. The docs are almost nonexistent at this point ;)

**Pull request closed without merging**
